/* The following code was generated by JFlex 1.4.3 on 5/11/21 17:57 */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/11/21 17:57 from the specification file
 * <tt>C:/Users/Usuario 1/Desktop/Proyecto-Compilador/Compilador/src/codigo/Lexico.flex</tt>
 */
class Lexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\11\1\13\2\0\1\7\22\0\1\7\1\47\1\12\2\0"+
    "\1\45\2\0\1\61\1\62\1\41\1\43\1\67\1\44\1\6\1\40"+
    "\1\5\11\4\1\57\1\60\1\50\1\42\1\51\2\0\1\52\2\2"+
    "\1\54\11\2\1\53\1\55\1\37\1\2\1\56\10\2\1\63\1\0"+
    "\1\64\1\46\1\3\1\0\1\21\1\25\1\23\1\24\1\14\1\31"+
    "\1\36\1\33\1\27\2\1\1\22\1\32\1\15\1\20\1\35\1\1"+
    "\1\17\1\10\1\16\1\26\1\30\1\1\1\34\2\1\1\65\1\0"+
    "\1\66\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\2\4\1\5\2\6"+
    "\1\7\1\10\1\11\14\2\1\3\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\1\1\21\1\22\2\3"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\6\1\2\2\3\1\0\1\6\1\33\1\0\1\34"+
    "\23\2\1\3\1\6\1\0\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\3\1\43\1\44\2\0\1\45\1\4"+
    "\30\2\1\3\1\0\1\46\2\0\1\4\1\0\1\45"+
    "\1\0\1\47\5\2\1\50\1\51\24\2\1\3\1\6"+
    "\7\2\1\52\1\2\1\53\7\2\1\54\2\2\1\55"+
    "\4\2\1\3\1\2\1\56\4\2\1\57\16\2\1\3"+
    "\10\2\1\60\2\2\1\61\1\2\1\62\5\2\1\3"+
    "\1\63\1\64\1\65\1\66\3\2\1\67\3\2\1\70"+
    "\2\2\1\71\1\72\1\3\5\2\1\73\2\2\1\74"+
    "\1\2\1\75\1\2\1\76\1\2\1\77\1\2\1\100"+
    "\1\101\1\102\1\103";

  private static int [] zzUnpackAction() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\70"+
    "\0\u0188\0\u01c0\0\70\0\u01f8\0\70\0\u0230\0\u0268\0\u02a0"+
    "\0\u02d8\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460"+
    "\0\u0498\0\u04d0\0\u0508\0\70\0\u0540\0\u0578\0\u05b0\0\70"+
    "\0\70\0\u05e8\0\u0620\0\u0658\0\u0690\0\u06c8\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\70\0\70\0\u0700\0\u0738"+
    "\0\u0770\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u01f8\0\u01f8\0\u0888"+
    "\0\u08c0\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48"+
    "\0\u0a80\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08"+
    "\0\u0c40\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\70\0\70\0\70"+
    "\0\70\0\70\0\70\0\u0d58\0\250\0\70\0\u0d90\0\u0dc8"+
    "\0\u0e00\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0f88"+
    "\0\u0fc0\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148"+
    "\0\u1180\0\u11b8\0\u11f0\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308"+
    "\0\u1340\0\u1378\0\u13b0\0\u13e8\0\250\0\u1420\0\u1458\0\u1490"+
    "\0\u0e00\0\u14c8\0\u14c8\0\160\0\u1500\0\u1538\0\u1570\0\u15a8"+
    "\0\u15e0\0\160\0\160\0\u1618\0\u1650\0\u1688\0\u16c0\0\u16f8"+
    "\0\u1730\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u18b8"+
    "\0\u18f0\0\u1928\0\u1960\0\u1998\0\u19d0\0\u1a08\0\u1a40\0\u1a78"+
    "\0\u0d20\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58\0\u1b90\0\u1bc8\0\u1c00"+
    "\0\160\0\u1c38\0\160\0\u1c70\0\u1ca8\0\u1ce0\0\u1d18\0\u1d50"+
    "\0\u1d88\0\u1dc0\0\160\0\u1df8\0\u1e30\0\160\0\u1e68\0\u1ea0"+
    "\0\u1ed8\0\u1f10\0\u1f48\0\u1f80\0\160\0\u1fb8\0\u1ff0\0\u2028"+
    "\0\u2060\0\160\0\u2098\0\u20d0\0\u2108\0\u2140\0\u2178\0\u21b0"+
    "\0\u21e8\0\u2220\0\u2258\0\u2290\0\u22c8\0\u2300\0\u2338\0\u2370"+
    "\0\u23a8\0\u23e0\0\u2418\0\u2450\0\u2488\0\u24c0\0\u24f8\0\u2530"+
    "\0\u2568\0\160\0\u25a0\0\u25d8\0\160\0\u2610\0\160\0\u2648"+
    "\0\u2680\0\u26b8\0\u26f0\0\u2728\0\u2760\0\160\0\160\0\160"+
    "\0\160\0\u2798\0\u27d0\0\u2808\0\160\0\u2840\0\u2878\0\u28b0"+
    "\0\160\0\u28e8\0\u2920\0\160\0\160\0\u2958\0\u2990\0\u29c8"+
    "\0\u2a00\0\u2a38\0\u2a70\0\160\0\u2aa8\0\u2ae0\0\u0770\0\u2b18"+
    "\0\160\0\u2b50\0\160\0\u2b88\0\160\0\u2bc0\0\160\0\160"+
    "\0\160\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\3\1\20"+
    "\3\3\1\21\1\22\1\23\1\3\1\24\1\25\1\26"+
    "\1\27\1\30\1\3\1\31\1\3\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\2\4\1\46\1\4\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\71\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\23\3\32\0\1\61"+
    "\2\4\2\62\2\0\1\61\3\0\23\61\1\4\12\0"+
    "\5\4\12\0\1\3\1\4\1\5\2\60\2\0\1\3"+
    "\3\0\23\3\1\4\12\0\5\4\15\0\2\6\1\63"+
    "\67\0\1\63\70\0\2\11\56\0\1\11\1\0\1\3"+
    "\1\0\1\3\2\60\1\0\1\11\1\64\3\0\13\3"+
    "\1\65\7\3\30\0\1\11\12\66\1\67\1\0\54\66"+
    "\1\0\1\3\1\0\1\3\2\60\2\0\1\70\3\0"+
    "\1\3\1\71\4\3\1\72\11\3\1\73\2\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\12\3"+
    "\1\74\10\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\75\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\4\3\1\76\1\77\1\100"+
    "\14\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\101\22\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\4\3\1\102\16\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\1\3\1\103"+
    "\21\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\104\22\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\5\3\1\105\15\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\1\106\12\3"+
    "\1\107\7\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\5\3\1\110\15\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\3\3\1\111\6\3"+
    "\1\112\10\3\32\0\1\61\2\4\2\62\2\0\1\61"+
    "\3\0\3\61\1\113\17\61\1\4\12\0\5\4\51\0"+
    "\1\114\1\115\70\0\1\116\70\0\1\117\70\0\1\120"+
    "\65\0\1\121\67\0\1\122\67\0\1\123\26\0\1\61"+
    "\2\4\2\62\2\0\1\61\3\0\23\61\1\4\12\0"+
    "\1\4\1\124\3\4\12\0\1\61\2\4\2\62\2\0"+
    "\1\61\3\0\23\61\1\4\12\0\4\4\1\125\17\0"+
    "\1\126\2\11\56\0\1\11\1\0\1\3\1\0\1\3"+
    "\2\60\1\127\1\0\1\3\3\0\23\3\32\0\1\61"+
    "\1\0\1\61\2\62\2\0\1\61\3\0\23\61\32\0"+
    "\1\61\1\0\1\61\2\62\1\130\1\0\1\61\3\0"+
    "\23\61\35\0\1\131\1\132\63\0\1\3\1\0\1\3"+
    "\2\60\1\0\1\11\1\64\3\0\23\3\30\0\1\11"+
    "\1\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\3\1\133\21\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\7\3\1\134\13\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\2\3\1\135"+
    "\20\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\13\3\1\136\7\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\2\3\1\137\20\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\6\3"+
    "\1\140\14\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\5\3\1\141\15\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\3\1\142\21\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\10\3\1\143\12\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\5\3\1\144\15\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\145\3\0\7\3\1\146"+
    "\4\3\1\147\6\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\6\3\1\150\14\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\151\3\0\7\3\1\152"+
    "\13\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\3\3\1\153\17\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\6\3\1\154\14\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\2\3"+
    "\1\155\20\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\156\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\7\3\1\157\13\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\4\3"+
    "\1\160\6\3\1\161\7\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\11\3\1\162\11\3\32\0"+
    "\1\61\1\0\1\61\2\62\2\0\1\61\3\0\13\61"+
    "\1\163\7\61\31\0\13\114\1\0\54\114\13\115\1\0"+
    "\25\115\1\164\26\115\1\0\1\61\2\4\2\62\2\0"+
    "\1\61\3\0\23\61\1\4\12\0\2\4\1\165\2\4"+
    "\15\0\1\166\1\3\66\0\1\167\1\61\66\0\1\170"+
    "\1\171\66\0\1\172\2\173\62\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\4\3\1\174\16\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\3\3"+
    "\1\175\17\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\176\3\3\1\177\16\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\16\3\1\200"+
    "\4\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\13\3\1\201\7\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\4\3\1\202\16\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\6\3"+
    "\1\203\14\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\204\3\0\23\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\205\22\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\206\3\0\23\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\2\3\1\207"+
    "\5\3\1\210\12\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\3\3\1\211\17\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\4\3\1\212"+
    "\16\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\213\22\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\2\3\1\214\20\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\215"+
    "\2\3\1\216\14\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\10\3\1\217\12\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\220\3\0\23\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\4\3"+
    "\1\221\16\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\3\1\222\21\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\223\22\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\2\3"+
    "\1\224\16\3\1\225\1\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\14\3\1\226\6\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\6\3"+
    "\1\227\14\3\32\0\1\61\1\0\1\61\2\62\2\0"+
    "\1\61\3\0\1\61\1\230\21\61\31\0\13\115\1\0"+
    "\24\115\1\231\1\164\26\115\4\0\1\3\1\166\66\0"+
    "\1\61\1\167\66\0\1\170\1\171\1\173\65\0\1\172"+
    "\1\173\63\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\13\3\1\232\7\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\3\3\1\233\17\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\1\3"+
    "\1\234\21\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\13\3\1\235\7\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\236\22\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\2\3"+
    "\1\237\20\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\3\1\240\21\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\241\22\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\3\3"+
    "\1\242\17\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\243\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\244\22\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\6\3\1\245"+
    "\14\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\5\3\1\246\15\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\5\3\1\247\15\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\1\250"+
    "\22\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\12\3\1\251\10\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\5\3\1\252\15\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\4\3"+
    "\1\253\16\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\10\3\1\254\12\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\2\3\1\255\20\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\3\3\1\256\17\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\257\22\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\13\3\1\260\7\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\5\3\1\261\15\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\13\3\1\262\7\3\32\0\1\61"+
    "\1\0\1\61\2\62\2\0\1\61\3\0\7\61\1\263"+
    "\13\61\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\11\3\1\264\11\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\4\3\1\265\16\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\7\3"+
    "\1\266\13\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\3\1\267\21\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\3\1\270\21\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\3\3\1\271\17\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\5\3\1\272\15\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\12\3\1\273"+
    "\10\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\16\3\1\274\4\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\14\3\1\275\6\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\1\3"+
    "\1\276\21\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\3\1\277\21\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\16\3\1\300\4\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\13\3\1\301\7\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\10\3\1\302\12\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\4\3\1\303"+
    "\16\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\3\3\1\304\17\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\22\3\1\305\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\1\306\22\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\10\3\1\307\12\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\7\3\1\310\13\3\32\0\1\61"+
    "\1\0\1\61\2\62\2\0\1\61\3\0\13\61\1\311"+
    "\7\61\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\13\3\1\312\7\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\313\22\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\5\3\1\314"+
    "\15\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\10\3\1\315\12\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\12\3\1\316\10\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\7\3"+
    "\1\317\13\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\320\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\321\22\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\4\3\1\322"+
    "\16\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\7\3\1\323\13\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\324\22\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\325"+
    "\17\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\326\22\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\327\3\0\23\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\5\3\1\330\15\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\13\3"+
    "\1\331\7\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\10\3\1\332\12\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\5\3\1\333\15\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\5\3\1\334\15\3\32\0\1\61\1\0\1\61\2\62"+
    "\2\0\1\61\3\0\21\61\1\335\1\61\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\336"+
    "\17\3\32\0\1\3\1\0\1\3\2\60\2\0\1\337"+
    "\3\0\23\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\3\3\1\340\17\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\341\22\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\7\3"+
    "\1\342\13\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\2\3\1\343\20\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\3\1\344\21\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\3\3\1\345\17\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\13\3\1\346\7\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\1\3\1\347"+
    "\21\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\3\3\1\350\17\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\351\3\0\23\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\10\3\1\352\12\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\5\3\1\353\15\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\354\3\0\23\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\355\3\0\23\3\32\0\1\61\1\0"+
    "\1\61\2\62\2\0\1\61\3\0\5\61\1\356\15\61"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\2\3\1\357\20\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\4\3\1\360\16\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\2\3\1\361"+
    "\20\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\5\3\1\362\15\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\2\3\1\363\20\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\4\3"+
    "\1\364\16\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\5\3\1\365\15\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\10\3\1\366\12\3"+
    "\32\0\1\61\1\0\1\61\2\62\2\0\1\61\3\0"+
    "\6\61\1\367\14\61\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\4\3\1\370\16\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\371"+
    "\17\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\5\3\1\372\15\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\3\3\1\373\17\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\5\3"+
    "\1\374\15\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\375\3\0\23\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\376\22\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\3\3\1\377\17\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\3\3\1\u0100\17\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\3\3\1\u0101\17\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\u0102\3\0\23\3\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11256];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\2\1\1\11\1\1\1\11"+
    "\16\1\1\11\3\1\2\11\5\1\10\11\4\1\1\0"+
    "\2\1\1\0\26\1\1\0\6\11\2\1\1\11\2\0"+
    "\33\1\1\0\1\1\2\0\1\1\1\0\1\1\1\0"+
    "\207\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[258];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 144) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 68: break;
        case 34: 
          { lexeme=yytext();return MayorIgual;
          }
        case 69: break;
        case 17: 
          { lexeme=yytext();return Menor;
          }
        case 70: break;
        case 22: 
          { lexeme=yytext();return ParentesisC;
          }
        case 71: break;
        case 56: 
          { lexeme=yytext(); return Mientras;
          }
        case 72: break;
        case 35: 
          { lexeme=yytext();return Or;
          }
        case 73: break;
        case 62: 
          { lexeme=yytext(); return Instanciar;
          }
        case 74: break;
        case 53: 
          { lexeme=yytext(); return Eliminar;
          }
        case 75: break;
        case 58: 
          { lexeme=yytext(); return Publicas;
          }
        case 76: break;
        case 10: 
          { lexeme=yytext();return Division;
          }
        case 77: break;
        case 64: 
          { lexeme=yytext(); return Constructor;
          }
        case 78: break;
        case 55: 
          { lexeme=yytext(); return Devolver;
          }
        case 79: break;
        case 33: 
          { lexeme=yytext();return MenorIgual;
          }
        case 80: break;
        case 45: 
          { lexeme=yytext(); return Hacer;
          }
        case 81: break;
        case 9: 
          { return Linea;
          }
        case 82: break;
        case 44: 
          { lexeme=yytext(); return Falso;
          }
        case 83: break;
        case 28: 
          { lexeme=yytext(); return CadenaT;
          }
        case 84: break;
        case 11: 
          { lexeme=yytext();return Multiplicacion;
          }
        case 85: break;
        case 24: 
          { lexeme=yytext();return CorcheteC;
          }
        case 86: break;
        case 51: 
          { lexeme=yytext(); return Escribir;
          }
        case 87: break;
        case 39: 
          { lexeme=yytext(); return Sino;
          }
        case 88: break;
        case 42: 
          { lexeme=yytext(); return Clase;
          }
        case 89: break;
        case 66: 
          { lexeme=yytext(); return Incrementar;
          }
        case 90: break;
        case 25: 
          { lexeme=yytext();return LlaveA;
          }
        case 91: break;
        case 20: 
          { lexeme=yytext();return PuntoComa;
          }
        case 92: break;
        case 49: 
          { lexeme=yytext(); return Incluir;
          }
        case 93: break;
        case 41: 
          { lexeme=yytext(); return Real;
          }
        case 94: break;
        case 8: 
          { lexeme=yytext(); return Comillas;
          }
        case 95: break;
        case 60: 
          { lexeme=yytext(); return Principal;
          }
        case 96: break;
        case 67: 
          { lexeme=yytext(); return Propiedades;
          }
        case 97: break;
        case 47: 
          { lexeme=yytext(); return Cadena;
          }
        case 98: break;
        case 61: 
          { lexeme=yytext(); return Destructor;
          }
        case 99: break;
        case 63: 
          { lexeme=yytext(); return Protegidas;
          }
        case 100: break;
        case 5: 
          { lexeme=yytext();return Punto;
          }
        case 101: break;
        case 52: 
          { lexeme=yytext(); return Entonces;
          }
        case 102: break;
        case 48: 
          { lexeme=yytext(); return Boleano;
          }
        case 103: break;
        case 37: 
          { lexeme=yytext();return NumReal;
          }
        case 104: break;
        case 4: 
          { lexeme=yytext();return NumEntero;
          }
        case 105: break;
        case 14: 
          { lexeme=yytext();return Resta;
          }
        case 106: break;
        case 57: 
          { lexeme=yytext(); return Privadas;
          }
        case 107: break;
        case 38: 
          { lexeme=yytext();return And;
          }
        case 108: break;
        case 18: 
          { lexeme=yytext();return Mayor;
          }
        case 109: break;
        case 50: 
          { lexeme=yytext(); return Metodos;
          }
        case 110: break;
        case 29: 
          { lexeme=yytext();return Comparador;
          }
        case 111: break;
        case 21: 
          { lexeme=yytext();return ParentesisA;
          }
        case 112: break;
        case 65: 
          { lexeme=yytext(); return Decrementar;
          }
        case 113: break;
        case 3: 
          { lexeme=yytext(); return IdClase;
          }
        case 114: break;
        case 27: 
          { lexeme=yytext(); return Si;
          }
        case 115: break;
        case 59: 
          { lexeme=yytext(); return Verdadero;
          }
        case 116: break;
        case 36: 
          { lexeme=yytext();return Coma;
          }
        case 117: break;
        case 26: 
          { lexeme=yytext();return LlaveC;
          }
        case 118: break;
        case 1: 
          { return ERROR;
          }
        case 119: break;
        case 31: 
          { lexeme=yytext();return Decremento;
          }
        case 120: break;
        case 46: 
          { lexeme=yytext(); return Entero;
          }
        case 121: break;
        case 32: 
          { lexeme=yytext();return Diferente;
          }
        case 122: break;
        case 13: 
          { lexeme=yytext();return Suma;
          }
        case 123: break;
        case 40: 
          { lexeme=yytext(); return Nulo;
          }
        case 124: break;
        case 30: 
          { lexeme=yytext();return Incremento;
          }
        case 125: break;
        case 16: 
          { lexeme=yytext();return Exponenciacion;
          }
        case 126: break;
        case 6: 
          { /*Ignore*/
          }
        case 127: break;
        case 12: 
          { lexeme=yytext();return Igual;
          }
        case 128: break;
        case 7: 
          { lexeme=yytext(); return Tabulador;
          }
        case 129: break;
        case 23: 
          { lexeme=yytext();return CorcheteA;
          }
        case 130: break;
        case 43: 
          { lexeme=yytext(); return Desde;
          }
        case 131: break;
        case 15: 
          { lexeme=yytext();return Modulo;
          }
        case 132: break;
        case 19: 
          { lexeme=yytext();return DosPuntos;
          }
        case 133: break;
        case 54: 
          { lexeme=yytext(); return Extiende;
          }
        case 134: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
