/* The following code was generated by JFlex 1.4.3 on 16/11/21 16:10 */

package codigo;
import java_cup.runtime.Symbol;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 16/11/21 16:10 from the specification file
 * <tt>C:/Users/Usuario 1/Desktop/Proyecto-Compilador/Compilador/src/codigo/LexicoCup.flex</tt>
 */
class LexicoCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  9, 11,  0,  0,  7,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     7, 39, 10,  0,  0, 37,  0,  0, 49, 50, 33, 35, 55, 36,  6, 32, 
     5,  4,  4,  4,  4,  4,  4,  4,  4,  4, 47, 48, 40, 34, 41,  0, 
     0, 42,  2,  2, 44,  2,  2,  2,  2,  2,  2,  2,  2,  2, 43, 45, 
    31,  2, 46,  2,  2,  2,  2,  2,  2,  2,  2, 51,  0, 52, 38,  3, 
     0, 17, 21, 19, 20, 12, 25, 30, 27, 23,  1,  1, 18, 26, 13, 16, 
    29,  1, 15,  8, 14, 22, 24,  1, 28,  1,  1, 53,  0, 54,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\2\4\1\5\2\6"+
    "\1\7\1\10\15\2\1\3\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\1\1\20\1\21\2\3\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\6"+
    "\1\2\2\3\1\0\1\6\1\32\1\0\1\33\24\2"+
    "\1\3\1\6\1\0\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\3\1\42\1\43\2\0\1\44\1\4\31\2"+
    "\1\3\1\0\1\45\2\0\1\4\1\0\1\44\1\0"+
    "\1\46\5\2\1\47\1\50\1\51\24\2\1\3\1\6"+
    "\7\2\1\52\1\2\1\53\7\2\1\54\2\2\1\55"+
    "\4\2\1\3\1\2\1\56\4\2\1\57\16\2\1\3"+
    "\10\2\1\60\2\2\1\61\1\2\1\62\5\2\1\3"+
    "\1\63\1\64\1\65\1\66\3\2\1\67\3\2\1\70"+
    "\2\2\1\71\1\72\1\3\5\2\1\73\2\2\1\74"+
    "\1\2\1\75\1\2\1\76\1\2\1\77\1\2\1\100"+
    "\1\101\1\102\1\103";

  private static int [] zzUnpackAction() {
    int [] result = new int[261];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\160\0\250\0\340\0\u0118\0\u0150\0\70"+
    "\0\u0188\0\u01c0\0\70\0\u01f8\0\u0230\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\70\0\u0578\0\u05b0\0\u05e8\0\70"+
    "\0\70\0\u0620\0\u0658\0\u0690\0\u06c8\0\u0700\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\70\0\70\0\u0738\0\u0770"+
    "\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888\0\u01f8\0\u01f8\0\u08c0"+
    "\0\u08f8\0\u0930\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48\0\u0a80"+
    "\0\u0ab8\0\u0af0\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40"+
    "\0\u0c78\0\u0cb0\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\70\0\70"+
    "\0\70\0\70\0\70\0\70\0\u0dc8\0\250\0\70\0\u0e00"+
    "\0\u0e38\0\u0e70\0\u0ea8\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0"+
    "\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180"+
    "\0\u11b8\0\u11f0\0\u1228\0\u1260\0\u1298\0\u12d0\0\u1308\0\u1340"+
    "\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458\0\u1490\0\250\0\u14c8"+
    "\0\u1500\0\u1538\0\u0e70\0\u1570\0\u1570\0\160\0\u15a8\0\u15e0"+
    "\0\u1618\0\u1650\0\u1688\0\160\0\160\0\160\0\u16c0\0\u16f8"+
    "\0\u1730\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u1880\0\u18b8"+
    "\0\u18f0\0\u1928\0\u1960\0\u1998\0\u19d0\0\u1a08\0\u1a40\0\u1a78"+
    "\0\u1ab0\0\u1ae8\0\u1b20\0\u0d90\0\u1b58\0\u1b90\0\u1bc8\0\u1c00"+
    "\0\u1c38\0\u1c70\0\u1ca8\0\160\0\u1ce0\0\160\0\u1d18\0\u1d50"+
    "\0\u1d88\0\u1dc0\0\u1df8\0\u1e30\0\u1e68\0\160\0\u1ea0\0\u1ed8"+
    "\0\160\0\u1f10\0\u1f48\0\u1f80\0\u1fb8\0\u1ff0\0\u2028\0\160"+
    "\0\u2060\0\u2098\0\u20d0\0\u2108\0\160\0\u2140\0\u2178\0\u21b0"+
    "\0\u21e8\0\u2220\0\u2258\0\u2290\0\u22c8\0\u2300\0\u2338\0\u2370"+
    "\0\u23a8\0\u23e0\0\u2418\0\u2450\0\u2488\0\u24c0\0\u24f8\0\u2530"+
    "\0\u2568\0\u25a0\0\u25d8\0\u2610\0\160\0\u2648\0\u2680\0\160"+
    "\0\u26b8\0\160\0\u26f0\0\u2728\0\u2760\0\u2798\0\u27d0\0\u2808"+
    "\0\160\0\160\0\160\0\160\0\u2840\0\u2878\0\u28b0\0\160"+
    "\0\u28e8\0\u2920\0\u2958\0\160\0\u2990\0\u29c8\0\160\0\160"+
    "\0\u2a00\0\u2a38\0\u2a70\0\u2aa8\0\u2ae0\0\u2b18\0\160\0\u2b50"+
    "\0\u2b88\0\u07a8\0\u2bc0\0\160\0\u2bf8\0\160\0\u2c30\0\160"+
    "\0\u2c68\0\160\0\160\0\160\0\160";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[261];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\11\1\15\1\16\1\3\1\17"+
    "\2\3\1\20\1\21\1\22\1\23\1\3\1\24\1\25"+
    "\1\26\1\27\1\30\1\3\1\31\1\3\1\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\2\4\1\46\1\4\1\47\1\50\1\51"+
    "\1\52\1\53\1\54\1\55\1\56\1\57\71\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\23\3\32\0"+
    "\1\61\2\4\2\62\2\0\1\61\3\0\23\61\1\4"+
    "\12\0\5\4\12\0\1\3\1\4\1\5\2\60\2\0"+
    "\1\3\3\0\23\3\1\4\12\0\5\4\15\0\2\6"+
    "\1\63\67\0\1\63\70\0\2\11\2\0\1\11\53\0"+
    "\1\11\1\0\1\3\1\0\1\3\2\60\1\0\1\11"+
    "\1\64\2\0\1\11\13\3\1\65\7\3\30\0\1\11"+
    "\12\66\1\67\1\0\54\66\1\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\70\3\0\1\3\1\71\4\3\1\72"+
    "\11\3\1\73\2\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\12\3\1\74\10\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\1\75\22\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\76\22\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\4\3\1\77\1\100\1\101\14\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\1\102"+
    "\22\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\4\3\1\103\16\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\3\1\104\21\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\1\105"+
    "\22\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\5\3\1\106\15\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\107\12\3\1\110\7\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\5\3\1\111\15\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\3\3\1\112\6\3\1\113\10\3"+
    "\32\0\1\61\2\4\2\62\2\0\1\61\3\0\3\61"+
    "\1\114\17\61\1\4\12\0\5\4\51\0\1\115\1\116"+
    "\70\0\1\117\70\0\1\120\70\0\1\121\65\0\1\122"+
    "\67\0\1\123\67\0\1\124\26\0\1\61\2\4\2\62"+
    "\2\0\1\61\3\0\23\61\1\4\12\0\1\4\1\125"+
    "\3\4\12\0\1\61\2\4\2\62\2\0\1\61\3\0"+
    "\23\61\1\4\12\0\4\4\1\126\17\0\1\127\2\11"+
    "\2\0\1\11\53\0\1\11\1\0\1\3\1\0\1\3"+
    "\2\60\1\130\1\0\1\3\3\0\23\3\32\0\1\61"+
    "\1\0\1\61\2\62\2\0\1\61\3\0\23\61\32\0"+
    "\1\61\1\0\1\61\2\62\1\131\1\0\1\61\3\0"+
    "\23\61\35\0\1\132\1\133\63\0\1\3\1\0\1\3"+
    "\2\60\1\0\1\11\1\64\2\0\1\11\23\3\30\0"+
    "\1\11\1\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\3\1\134\21\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\7\3\1\135\13\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\2\3"+
    "\1\136\20\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\13\3\1\137\7\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\2\3\1\140\20\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\6\3\1\141\14\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\5\3\1\142\15\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\1\143\22\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\3\1\144\21\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\10\3\1\145\12\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\5\3\1\146"+
    "\15\3\32\0\1\3\1\0\1\3\2\60\2\0\1\147"+
    "\3\0\7\3\1\150\4\3\1\151\6\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\6\3\1\152"+
    "\14\3\32\0\1\3\1\0\1\3\2\60\2\0\1\153"+
    "\3\0\7\3\1\154\13\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\3\3\1\155\17\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\6\3"+
    "\1\156\14\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\2\3\1\157\20\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\160\22\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\7\3"+
    "\1\161\13\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\4\3\1\162\6\3\1\163\7\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\11\3"+
    "\1\164\11\3\32\0\1\61\1\0\1\61\2\62\2\0"+
    "\1\61\3\0\13\61\1\165\7\61\31\0\13\115\1\0"+
    "\54\115\13\116\1\0\25\116\1\166\26\116\1\0\1\61"+
    "\2\4\2\62\2\0\1\61\3\0\23\61\1\4\12\0"+
    "\2\4\1\167\2\4\15\0\1\170\1\3\66\0\1\171"+
    "\1\61\66\0\1\172\1\173\66\0\1\174\2\175\62\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\4\3"+
    "\1\176\16\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\3\3\1\177\17\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\200\3\3\1\201"+
    "\16\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\16\3\1\202\4\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\13\3\1\203\7\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\4\3"+
    "\1\204\16\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\6\3\1\205\14\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\3\3\1\206\17\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\207\3\0"+
    "\23\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\210\22\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\211\3\0\23\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\2\3\1\212\5\3\1\213"+
    "\12\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\3\3\1\214\17\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\4\3\1\215\16\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\1\216"+
    "\22\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\2\3\1\217\20\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\3\3\1\220\2\3\1\221"+
    "\14\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\10\3\1\222\12\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\223\3\0\23\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\4\3\1\224\16\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\3\1\225\21\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\226\22\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\2\3\1\227\16\3"+
    "\1\230\1\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\14\3\1\231\6\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\6\3\1\232\14\3"+
    "\32\0\1\61\1\0\1\61\2\62\2\0\1\61\3\0"+
    "\1\61\1\233\21\61\31\0\13\116\1\0\24\116\1\234"+
    "\1\166\26\116\4\0\1\3\1\170\66\0\1\61\1\171"+
    "\66\0\1\172\1\173\1\175\65\0\1\174\1\175\63\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\13\3"+
    "\1\235\7\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\3\3\1\236\17\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\3\1\237\21\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\13\3\1\240\7\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\241\22\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\2\3\1\242\20\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\3\1\243\21\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\244\22\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\3\3\1\245\17\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\246\22\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\247\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\6\3\1\250\14\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\5\3"+
    "\1\251\15\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\5\3\1\252\15\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\253\22\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\12\3"+
    "\1\254\10\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\5\3\1\255\15\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\4\3\1\256\16\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\10\3\1\257\12\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\2\3\1\260\20\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\261"+
    "\17\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\262\22\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\13\3\1\263\7\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\5\3\1\264"+
    "\15\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\13\3\1\265\7\3\32\0\1\61\1\0\1\61"+
    "\2\62\2\0\1\61\3\0\7\61\1\266\13\61\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\11\3"+
    "\1\267\11\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\4\3\1\270\16\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\7\3\1\271\13\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\3\1\272\21\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\3\1\273\21\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\274"+
    "\17\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\5\3\1\275\15\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\12\3\1\276\10\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\16\3"+
    "\1\277\4\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\14\3\1\300\6\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\1\3\1\301\21\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\3\1\302\21\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\16\3\1\303\4\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\13\3\1\304"+
    "\7\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\10\3\1\305\12\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\4\3\1\306\16\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\3\3"+
    "\1\307\17\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\22\3\1\310\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\311\22\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\10\3\1\312"+
    "\12\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\7\3\1\313\13\3\32\0\1\61\1\0\1\61"+
    "\2\62\2\0\1\61\3\0\13\61\1\314\7\61\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\13\3"+
    "\1\315\7\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\316\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\5\3\1\317\15\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\10\3"+
    "\1\320\12\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\12\3\1\321\10\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\7\3\1\322\13\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\1\323\22\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\324\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\4\3\1\325\16\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\7\3"+
    "\1\326\13\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\1\327\22\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\3\3\1\330\17\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\1\331"+
    "\22\3\32\0\1\3\1\0\1\3\2\60\2\0\1\332"+
    "\3\0\23\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\5\3\1\333\15\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\13\3\1\334\7\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\10\3\1\335\12\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\5\3\1\336\15\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\5\3\1\337"+
    "\15\3\32\0\1\61\1\0\1\61\2\62\2\0\1\61"+
    "\3\0\21\61\1\340\1\61\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\3\3\1\341\17\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\342\3\0\23\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\3\3\1\343\17\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\344\22\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\7\3\1\345\13\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\2\3\1\346\20\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\1\3\1\347\21\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\350"+
    "\17\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\13\3\1\351\7\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\1\3\1\352\21\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\3\3"+
    "\1\353\17\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\354\3\0\23\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\10\3\1\355\12\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\5\3\1\356"+
    "\15\3\32\0\1\3\1\0\1\3\2\60\2\0\1\357"+
    "\3\0\23\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\360\3\0\23\3\32\0\1\61\1\0\1\61\2\62"+
    "\2\0\1\61\3\0\5\61\1\361\15\61\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\2\3\1\362"+
    "\20\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\4\3\1\363\16\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\2\3\1\364\20\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\5\3"+
    "\1\365\15\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\2\3\1\366\20\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\4\3\1\367\16\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\3\3\0"+
    "\5\3\1\370\15\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\10\3\1\371\12\3\32\0\1\61"+
    "\1\0\1\61\2\62\2\0\1\61\3\0\6\61\1\372"+
    "\14\61\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\4\3\1\373\16\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\3\3\0\3\3\1\374\17\3\32\0"+
    "\1\3\1\0\1\3\2\60\2\0\1\3\3\0\5\3"+
    "\1\375\15\3\32\0\1\3\1\0\1\3\2\60\2\0"+
    "\1\3\3\0\3\3\1\376\17\3\32\0\1\3\1\0"+
    "\1\3\2\60\2\0\1\3\3\0\5\3\1\377\15\3"+
    "\32\0\1\3\1\0\1\3\2\60\2\0\1\u0100\3\0"+
    "\23\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\1\u0101\22\3\32\0\1\3\1\0\1\3\2\60"+
    "\2\0\1\3\3\0\3\3\1\u0102\17\3\32\0\1\3"+
    "\1\0\1\3\2\60\2\0\1\3\3\0\3\3\1\u0103"+
    "\17\3\32\0\1\3\1\0\1\3\2\60\2\0\1\3"+
    "\3\0\3\3\1\u0104\17\3\32\0\1\3\1\0\1\3"+
    "\2\60\2\0\1\u0105\3\0\23\3\31\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11424];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\2\1\1\11\20\1\1\11"+
    "\3\1\2\11\5\1\10\11\4\1\1\0\2\1\1\0"+
    "\27\1\1\0\6\11\2\1\1\11\2\0\34\1\1\0"+
    "\1\1\2\0\1\1\1\0\1\1\1\0\210\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[261];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexicoCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexicoCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 29: 
          { return new Symbol(sym.Incremento, yychar, yyline, yytext());
          }
        case 68: break;
        case 15: 
          { return new Symbol(sym.Exponenciacion, yychar, yyline, yytext());
          }
        case 69: break;
        case 66: 
          { return new Symbol(sym.Incrementar, yychar, yyline, yytext());
          }
        case 70: break;
        case 36: 
          { return new Symbol(sym.NumReal, yychar, yyline, yytext());
          }
        case 71: break;
        case 47: 
          { return new Symbol(sym.Cadena, yychar, yyline, yytext());
          }
        case 72: break;
        case 61: 
          { return new Symbol(sym.Destructor, yychar, yyline, yytext());
          }
        case 73: break;
        case 28: 
          { return new Symbol(sym.Comparador, yychar, yyline, yytext());
          }
        case 74: break;
        case 53: 
          { return new Symbol(sym.Eliminar, yychar, yyline, yytext());
          }
        case 75: break;
        case 24: 
          { return new Symbol(sym.LlaveA, yychar, yyline, yytext());
          }
        case 76: break;
        case 27: 
          { return new Symbol(sym.CadenaT, yychar, yyline, yytext());
          }
        case 77: break;
        case 59: 
          { return new Symbol(sym.Verdadero, yychar, yyline, yytext());
          }
        case 78: break;
        case 9: 
          { return new Symbol(sym.Division, yychar, yyline, yytext());
          }
        case 79: break;
        case 67: 
          { return new Symbol(sym.Propiedades, yychar, yyline, yytext());
          }
        case 80: break;
        case 57: 
          { return new Symbol(sym.Privadas, yychar, yyline, yytext());
          }
        case 81: break;
        case 30: 
          { return new Symbol(sym.Decremento, yychar, yyline, yytext());
          }
        case 82: break;
        case 54: 
          { return new Symbol(sym.Extiende, yychar, yyline, yytext());
          }
        case 83: break;
        case 32: 
          { return new Symbol(sym.MenorIgual, yychar, yyline, yytext());
          }
        case 84: break;
        case 26: 
          { return new Symbol(sym.Si, yychar, yyline, yytext());
          }
        case 85: break;
        case 8: 
          { return new Symbol(sym.Comillas, yychar, yyline, yytext());
          }
        case 86: break;
        case 45: 
          { return new Symbol(sym.Hacer, yychar, yyline, yytext());
          }
        case 87: break;
        case 13: 
          { return new Symbol(sym.Resta, yychar, yyline, yytext());
          }
        case 88: break;
        case 58: 
          { return new Symbol(sym.Publicas, yychar, yyline, yytext());
          }
        case 89: break;
        case 55: 
          { return new Symbol(sym.Devolver, yychar, yyline, yytext());
          }
        case 90: break;
        case 41: 
          { return new Symbol(sym.Leer, yychar, yyline, yytext());
          }
        case 91: break;
        case 19: 
          { return new Symbol(sym.PuntoComa, yychar, yyline, yytext());
          }
        case 92: break;
        case 17: 
          { return new Symbol(sym.Mayor, yychar, yyline, yytext());
          }
        case 93: break;
        case 22: 
          { return new Symbol(sym.CorcheteA, yychar, yyline, yytext());
          }
        case 94: break;
        case 20: 
          { return new Symbol(sym.ParentesisA, yychar, yyline, yytext());
          }
        case 95: break;
        case 40: 
          { return new Symbol(sym.Real, yychar, yyline, yytext());
          }
        case 96: break;
        case 39: 
          { return new Symbol(sym.Nulo, yychar, yyline, yytext());
          }
        case 97: break;
        case 25: 
          { return new Symbol(sym.LlaveC, yychar, yyline, yytext());
          }
        case 98: break;
        case 18: 
          { return new Symbol(sym.DosPuntos, yychar, yyline, yytext());
          }
        case 99: break;
        case 14: 
          { return new Symbol(sym.Modulo, yychar, yyline, yytext());
          }
        case 100: break;
        case 4: 
          { return new Symbol(sym.NumEntero, yychar, yyline, yytext());
          }
        case 101: break;
        case 16: 
          { return new Symbol(sym.Menor, yychar, yyline, yytext());
          }
        case 102: break;
        case 56: 
          { return new Symbol(sym.Mientras, yychar, yyline, yytext());
          }
        case 103: break;
        case 37: 
          { return new Symbol(sym.And, yychar, yyline, yytext());
          }
        case 104: break;
        case 44: 
          { return new Symbol(sym.Falso, yychar, yyline, yytext());
          }
        case 105: break;
        case 46: 
          { return new Symbol(sym.Entero, yychar, yyline, yytext());
          }
        case 106: break;
        case 7: 
          { return new Symbol(sym.Tabulador, yychar, yyline, yytext());
          }
        case 107: break;
        case 51: 
          { return new Symbol(sym.Escribir, yychar, yyline, yytext());
          }
        case 108: break;
        case 43: 
          { return new Symbol(sym.Desde, yychar, yyline, yytext());
          }
        case 109: break;
        case 33: 
          { return new Symbol(sym.MayorIgual, yychar, yyline, yytext());
          }
        case 110: break;
        case 65: 
          { return new Symbol(sym.Decrementar, yychar, yyline, yytext());
          }
        case 111: break;
        case 42: 
          { return new Symbol(sym.Clase, yychar, yyline, yytext());
          }
        case 112: break;
        case 60: 
          { return new Symbol(sym.Principal, yychar, yyline, yytext());
          }
        case 113: break;
        case 52: 
          { return new Symbol(sym.Entonces, yychar, yyline, yytext());
          }
        case 114: break;
        case 62: 
          { return new Symbol(sym.Instanciar, yychar, yyline, yytext());
          }
        case 115: break;
        case 10: 
          { return new Symbol(sym.Multiplicacion, yychar, yyline, yytext());
          }
        case 116: break;
        case 63: 
          { return new Symbol(sym.Protegidas, yychar, yyline, yytext());
          }
        case 117: break;
        case 12: 
          { return new Symbol(sym.Suma, yychar, yyline, yytext());
          }
        case 118: break;
        case 23: 
          { return new Symbol(sym.CorcheteC, yychar, yyline, yytext());
          }
        case 119: break;
        case 21: 
          { return new Symbol(sym.ParentesisC, yychar, yyline, yytext());
          }
        case 120: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 121: break;
        case 31: 
          { return new Symbol(sym.Diferente, yychar, yyline, yytext());
          }
        case 122: break;
        case 3: 
          { return new Symbol(sym.IdClase, yychar, yyline, yytext());
          }
        case 123: break;
        case 34: 
          { return new Symbol(sym.Or, yychar, yyline, yytext());
          }
        case 124: break;
        case 5: 
          { return new Symbol(sym.Punto, yychar, yyline, yytext());
          }
        case 125: break;
        case 49: 
          { return new Symbol(sym.Incluir, yychar, yyline, yytext());
          }
        case 126: break;
        case 48: 
          { return new Symbol(sym.Boleano, yychar, yyline, yytext());
          }
        case 127: break;
        case 6: 
          { /*Ignore*/
          }
        case 128: break;
        case 50: 
          { return new Symbol(sym.Metodos, yychar, yyline, yytext());
          }
        case 129: break;
        case 11: 
          { return new Symbol(sym.Igual, yychar, yyline, yytext());
          }
        case 130: break;
        case 35: 
          { return new Symbol(sym.Coma, yychar, yyline, yytext());
          }
        case 131: break;
        case 2: 
          { return new Symbol(sym.Identificador, yychar, yyline, yytext());
          }
        case 132: break;
        case 64: 
          { return new Symbol(sym.Constructor, yychar, yyline, yytext());
          }
        case 133: break;
        case 38: 
          { return new Symbol(sym.Sino, yychar, yyline, yytext());
          }
        case 134: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
