
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 07 16:04:53 CST 2021
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 49;
  public static final int Destructor = 32;
  public static final int Entero = 2;
  public static final int Incremento = 40;
  public static final int Boleano = 5;
  public static final int CadenaT = 64;
  public static final int Coma = 58;
  public static final int PuntoComa = 51;
  public static final int Nulo = 6;
  public static final int Constructor = 31;
  public static final int Metodos = 24;
  public static final int LlaveC = 57;
  public static final int Diferente = 43;
  public static final int Decremento = 41;
  public static final int Incluir = 22;
  public static final int Real = 3;
  public static final int Clase = 20;
  public static final int LlaveA = 56;
  public static final int Menor = 47;
  public static final int Tabulador = 65;
  public static final int Principal = 28;
  public static final int Mayor = 46;
  public static final int Publicas = 25;
  public static final int Leer = 19;
  public static final int Punto = 59;
  public static final int Division = 37;
  public static final int Cadena = 4;
  public static final int Modulo = 38;
  public static final int Falso = 12;
  public static final int Hacer = 17;
  public static final int EOF = 0;
  public static final int DosPuntos = 50;
  public static final int Decrementar = 16;
  public static final int CorcheteC = 55;
  public static final int And = 48;
  public static final int error = 1;
  public static final int CorcheteA = 54;
  public static final int Eliminar = 29;
  public static final int Incrementar = 15;
  public static final int Linea = 67;
  public static final int Devolver = 10;
  public static final int ERROR = 68;
  public static final int Comparador = 42;
  public static final int MenorIgual = 44;
  public static final int Entonces = 8;
  public static final int NumEntero = 62;
  public static final int Exponenciacion = 39;
  public static final int Propiedades = 23;
  public static final int Protegidas = 27;
  public static final int Identificador = 60;
  public static final int Si = 7;
  public static final int Privadas = 26;
  public static final int Resta = 35;
  public static final int Desde = 13;
  public static final int MayorIgual = 45;
  public static final int Sino = 9;
  public static final int Escribir = 18;
  public static final int Mientras = 14;
  public static final int Extiende = 21;
  public static final int ParentesisC = 53;
  public static final int Multiplicacion = 36;
  public static final int Verdadero = 11;
  public static final int ParentesisA = 52;
  public static final int Instanciar = 30;
  public static final int NumReal = 63;
  public static final int Suma = 34;
  public static final int IdClase = 61;
  public static final int Igual = 33;
  public static final int Comillas = 66;
}

